# Stage 1
# FROM: Base image starten
FROM node:20 AS builder

# LABEL: Metadata
LABEL maintainer="NOVI"

# WORKDIR: Werkmapje in container
WORKDIR /app

# COPY: Bestanden van host naar container
COPY package*.json ./

# run npm run build
RUN npm ci

# COPY: Meer bestanden
COPY . .


# Stage 2
FROM node:20-alpine

# LABEL: Metadata
LABEL maintainer="NOVI"

# WORKDIR: Werkmapje in container
WORKDIR /app

# COPY: Bestanden van host naar container
COPY package*.json ./

# RUN: Commando's uitvoeren
RUN npm ci --only=production
RUN npm cache clean --force

# Cory form builder
COPY --from=builder /app/src ./src

# HEALTHCHECK: Health monitoring
HEALTHCHECK --interval=30s CMD ...

# EXPOSE: Port declaratie
EXPOSE 3000

# CMD: Default command
CMD ["node", "src/index.js"]




