name: Continuous Integration

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 24]

    steps:
      - run: echo "Starting workflow"
      - run: echo "Checking out codebase"
      - name: Checkout codebase
        uses: actions/checkout@v6

      - run: echo "Setting up Node.js"
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        
      - run: echo "Installing dependencies"
      - name: Install dependencies
        run: npm ci


      - run: echo "Running Unit tests"
      - name: Run Unit test
        run: npm test

      - name: Uplooad coverage
        uses: codecov/codecov-action@v6
        with:
          files: ./coverage/lcov.info

      - run: echo "Finished workflow"
